{
  "contest": 150,
  "handle": "0xDjango",
  "address": "0x886241e011a6c148bdd96b097eb27962f8a1c5f0",
  "risk": "2",
  "title": "Proxy multicall will fail because of use of .call() instead of .delegatecall()",
  "issueId": 12,
  "issueUrl": "https://github.com/code-423n4/2022-08-mimo-findings/issues/12"
}